name: Node.js App Deploy to EKS

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t node-app .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: autheticate ecr
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637423391401.dkr.ecr.us-east-1.amazonaws.com

      - name: tag image
        run: docker tag node-app:latest 637423391401.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

      - name: Push Image to ECR
        run: docker push 637423391401.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

